import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatDateAR } from './dateUtils';
import { CURRENCIES } from './constants';

// تحويل الصورة إلى base64
const getImageAsBase64 = async (imagePath) => {
  try {
    const response = await fetch(imagePath);
    const blob = await response.blob();
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch (error) {
    console.error('Error loading image:', error);
    return null;
  }
};

// ترجمات للغات المختلفة
const getTranslations = (lang = 'ar') => {
  const translations = {
    ar: {
      invoiceIn: 'فاتورة وارد',
      invoiceOut: 'فاتورة صادر',
      date: 'التاريخ',
      invoiceNumber: 'رقم الفاتورة',
      description: 'البيان',
      amount: 'المبلغ',
      category: 'التصنيف',
      vendor: 'المورد',
      customer: 'العميل',
      status: 'الحالة',
      signature: 'التوقيع',
      stamp: 'الختم',
      footer: 'تم إنشاء هذه الفاتورة تلقائياً من نظام إبراهيم للمحاسبة',
      itemName: 'اسم المنتج',
      quantity: 'الكمية',
      unitPrice: 'سعر الوحدة',
      total: 'الإجمالي',
      unit: 'الوحدة',
      items: 'المنتجات',
      totalAmount: 'المبلغ الإجمالي',
      reportDate: 'تاريخ التقرير',
      reportFooter: 'تم إنشاء هذا التقرير تلقائياً من نظام إبراهيم للمحاسبة'
    },
    en: {
      invoiceIn: 'Purchase Invoice',
      invoiceOut: 'Sales Invoice',
      date: 'Date',
      invoiceNumber: 'Invoice Number',
      description: 'Description',
      amount: 'Amount',
      category: 'Category',
      vendor: 'Vendor',
      customer: 'Customer',
      status: 'Status',
      signature: 'Signature',
      stamp: 'Stamp',
      footer: 'This invoice was automatically generated by Ibrahim Accounting System',
      itemName: 'Item Name',
      quantity: 'Quantity',
      unitPrice: 'Unit Price',
      total: 'Total',
      unit: 'Unit',
      items: 'Items',
      totalAmount: 'Total Amount',
      reportDate: 'Report Date',
      reportFooter: 'This report was automatically generated by Ibrahim Accounting System'
    },
    tr: {
      invoiceIn: 'Giriş Faturası',
      invoiceOut: 'Çıkış Faturası',
      date: 'Tarih',
      invoiceNumber: 'Fatura Numarası',
      description: 'Açıklama',
      amount: 'Tutar',
      category: 'Kategori',
      vendor: 'Tedarikçi',
      customer: 'Müşteri',
      status: 'Durum',
      signature: 'İmza',
      stamp: 'Mühür',
      footer: 'Bu fatura İbrahim Muhasebe Sistemi tarafından otomatik olarak oluşturulmuştur',
      itemName: 'Ürün Adı',
      quantity: 'Miktar',
      unitPrice: 'Birim Fiyat',
      total: 'Toplam',
      unit: 'Birim',
      items: 'Ürünler',
      totalAmount: 'Toplam Tutar',
      reportDate: 'Rapor Tarihi',
      reportFooter: 'Bu rapor İbrahim Muhasebe Sistemi tarafından otomatik olarak oluşturulmuştur'
    }
  };
  return translations[lang] || translations.ar;
};

// إنشاء PDF للفاتورة مع دعم لغات متعددة وعناصر
export const generateInvoicePDF = async (invoice, type, tenantName, logoPath = '/logo.png', language = 'ar', invoiceItems = []) => {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const t = getTranslations(language);
  const isRTL = language === 'ar';
  
  // تحميل الشعار
  let logoBase64 = null;
  try {
    logoBase64 = await getImageAsBase64(logoPath);
  } catch (error) {
    console.error('Logo not found, continuing without logo');
  }

  // رأس الصفحة
  let startY = 20;

  // الشعار في الأعلى
  if (logoBase64) {
    try {
      const logoSize = 30;
      const logoX = isRTL ? pageWidth - 25 : 20;
      doc.addImage(logoBase64, 'PNG', logoX, 10, logoSize, logoSize);
    } catch (error) {
      console.error('Error adding logo:', error);
    }
  }

  // استخدام autoTable لعرض معلومات الفاتورة (دعم أفضل للعربية)
  const headerData = [
    [isRTL ? t.invoiceNumber : t.invoiceNumber, invoice.invoice_number || invoice.id?.substring(0, 8) || '-'],
    [isRTL ? t.date : t.date, invoice.date ? formatDateAR(invoice.date, { year: 'numeric', month: 'long', day: 'numeric' }) : formatDateAR(new Date())],
  ];

  if (invoice.partner_name) {
    headerData.push([isRTL ? (type === 'in' ? t.vendor : t.customer) : (type === 'in' ? t.vendor : t.customer), invoice.partner_name]);
  }

  if (invoice.category) {
    headerData.push([isRTL ? t.category : t.category, invoice.category]);
  }

  if (invoice.status) {
    headerData.push([isRTL ? t.status : t.status, invoice.status]);
  }

  // جدول معلومات الفاتورة الأساسية - مع دعم أفضل للعربية
  autoTable(doc, {
    startY: startY,
    head: [[isRTL ? 'المعلومة' : 'Information', isRTL ? 'القيمة' : 'Value']],
    body: headerData,
    theme: 'plain',
    headStyles: { fillColor: [255, 140, 0], textColor: 255, fontStyle: 'bold' },
    styles: { 
      fontSize: 10, 
      halign: isRTL ? 'right' : 'left',
      font: 'helvetica', // jspdf-autotable يدعم العربية عبر Unicode
      fontStyle: 'normal'
    },
    margin: { left: 20, right: 20 },
    columnStyles: {
      0: { cellWidth: 50 },
      1: { cellWidth: 'auto' }
    }
  });

  startY = doc.lastAutoTable.finalY + 10;

  // العنوان
  autoTable(doc, {
    startY: startY,
    head: [[type === 'in' ? t.invoiceIn : t.invoiceOut]],
    body: [],
    theme: 'plain',
    headStyles: { fillColor: [255, 140, 0], textColor: 255, fontStyle: 'bold', fontSize: 18 },
    styles: { fontSize: 18, halign: 'center' },
    margin: { left: 20, right: 20 }
  });

  startY = doc.lastAutoTable.finalY + 5;

  // اسم المتجر
  if (tenantName) {
    autoTable(doc, {
      startY: startY,
      head: [[tenantName]],
      body: [],
      theme: 'plain',
      headStyles: { fillColor: [255, 255, 255], textColor: 0, fontStyle: 'bold', fontSize: 14 },
      styles: { fontSize: 14, halign: 'center' },
      margin: { left: 20, right: 20 }
    });
    startY = doc.lastAutoTable.finalY + 5;
  }

  // البيان
  if (invoice.description) {
    const descriptionData = [[t.description, invoice.description]];
    autoTable(doc, {
      startY: startY,
      head: [[isRTL ? 'البيان' : 'Description', isRTL ? 'القيمة' : 'Value']],
      body: descriptionData,
      theme: 'plain',
      headStyles: { fillColor: [240, 240, 240], textColor: 0, fontStyle: 'bold' },
      styles: { fontSize: 10, halign: isRTL ? 'right' : 'left' },
      margin: { left: 20, right: 20 }
    });
    startY = doc.lastAutoTable.finalY + 10;
  }

  // جدول المنتجات إذا كانت موجودة
  if (invoiceItems && invoiceItems.length > 0) {
    const itemsData = invoiceItems.map((item, index) => [
      (index + 1).toString(),
      item.item_name || item.name || '-',
      item.item_code || item.code || '-',
      parseFloat(item.quantity || 0).toString(),
      item.unit || 'piece',
      parseFloat(item.unit_price || 0).toLocaleString('ar-EG'),
      parseFloat(item.total_price || 0).toLocaleString('ar-EG')
    ]);

    autoTable(doc, {
      startY: startY,
      head: [[
        isRTL ? 'م' : '#',
        isRTL ? t.itemName : t.itemName,
        isRTL ? 'الكود' : 'Code',
        isRTL ? t.quantity : t.quantity,
        isRTL ? t.unit : t.unit,
        isRTL ? t.unitPrice : t.unitPrice,
        isRTL ? t.total : t.total
      ]],
      body: itemsData,
      theme: 'striped',
      headStyles: { fillColor: [255, 140, 0], textColor: 255, fontStyle: 'bold' },
      styles: { 
        fontSize: 9, 
        halign: isRTL ? 'right' : 'left',
        font: 'helvetica',
        fontStyle: 'normal'
      },
      margin: { left: 20, right: 20 },
      columnStyles: {
        0: { cellWidth: 15 },
        1: { cellWidth: 'auto' },
        2: { cellWidth: 30 },
        3: { cellWidth: 25 },
        4: { cellWidth: 25 },
        5: { cellWidth: 35 },
        6: { cellWidth: 35 }
      }
    });
    startY = doc.lastAutoTable.finalY + 10;
  }

  // المبلغ الإجمالي
  const currencyInfo = CURRENCIES[invoice.currency] || { symbol: invoice.currency, code: invoice.currency };
  const totalAmount = invoiceItems && invoiceItems.length > 0
    ? invoiceItems.reduce((sum, item) => sum + parseFloat(item.total_price || 0), 0)
    : parseFloat(invoice.amount || 0);

  const amountData = [[
    t.totalAmount,
    `${currencyInfo.symbol} ${totalAmount.toLocaleString('ar-EG', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
  ]];

  autoTable(doc, {
    startY: startY,
    head: [],
    body: amountData,
    theme: 'plain',
    styles: { fontSize: 12, fontStyle: 'bold', halign: isRTL ? 'right' : 'left' },
    margin: { left: 20, right: 20 },
    columnStyles: {
      0: { cellWidth: 50 },
      1: { cellWidth: 'auto', fontStyle: 'bold' }
    }
  });

  startY = doc.lastAutoTable.finalY + 15;

  // التوقيع والختم
  const signatureData = [
    [t.signature, ''],
    [t.stamp, '']
  ];

  autoTable(doc, {
    startY: startY,
    head: [],
    body: signatureData,
    theme: 'plain',
    styles: { fontSize: 10, halign: isRTL ? 'right' : 'left' },
    margin: { left: 20, right: 20 },
    columnStyles: {
      0: { cellWidth: 80 },
      1: { cellWidth: 'auto' }
    }
  });

  // التذييل
  const footerY = pageHeight - 15;
  autoTable(doc, {
    startY: footerY,
    head: [],
    body: [[t.footer]],
    theme: 'plain',
    styles: { fontSize: 7, textColor: [128, 128, 128], halign: 'center' },
    margin: { left: 20, right: 20 }
  });

  // علامة مائية للشعار
  if (logoBase64) {
    try {
      doc.setGState(doc.GState({ opacity: 0.05 }));
      const logoWidth = 100;
      const logoHeight = 100;
      const centerX = (pageWidth - logoWidth) / 2;
      const centerY = (pageHeight - logoHeight) / 2;
      doc.addImage(logoBase64, 'PNG', centerX, centerY, logoWidth, logoHeight);
      doc.setGState(doc.GState({ opacity: 1 }));
    } catch (error) {
      console.error('Error adding watermark:', error);
    }
  }

  return doc;
};

// إنشاء PDF للتقرير مع دعم لغات متعددة
export const generateReportPDF = async (title, data, columns, tenantName, logoPath = '/logo.png', language = 'ar') => {
  const doc = new jsPDF('l', 'mm', 'a4'); // Landscape للتقارير
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const t = getTranslations(language);
  const isRTL = language === 'ar';

  // تحميل الشعار
  let logoBase64 = null;
  try {
    logoBase64 = await getImageAsBase64(logoPath);
  } catch (error) {
    console.error('Logo not found');
  }

  // إضافة العلامة المائية في الخلفية (قبل أي محتوى)
  if (logoBase64) {
    try {
      doc.setGState(doc.GState({ opacity: 0.08 }));
      const logoWidth = 120;
      const logoHeight = 120;
      const centerX = (pageWidth - logoWidth) / 2;
      const centerY = (pageHeight - logoHeight) / 2;
      doc.addImage(logoBase64, 'PNG', centerX, centerY, logoWidth, logoHeight);
      doc.setGState(doc.GState({ opacity: 1 }));
    } catch (error) {
      console.error('Error adding watermark:', error);
    }
  }

  // العنوان
  autoTable(doc, {
    startY: 10,
    head: [[title]],
    body: [],
    theme: 'plain',
    headStyles: { fillColor: [255, 140, 0], textColor: 255, fontStyle: 'bold', fontSize: 18 },
    styles: { fontSize: 18, halign: 'center' },
    margin: { left: 15, right: 15 }
  });

  let startY = 20;

  // اسم المتجر
  if (tenantName) {
    autoTable(doc, {
      startY: startY,
      head: [[tenantName]],
      body: [],
      theme: 'plain',
      headStyles: { fillColor: [255, 255, 255], textColor: 0, fontStyle: 'bold', fontSize: 12 },
      styles: { fontSize: 12, halign: 'center' },
      margin: { left: 15, right: 15 }
    });
    startY = doc.lastAutoTable.finalY + 5;
  }

  // التاريخ
  const reportDate = [[t.reportDate, formatDateAR(new Date(), { year: 'numeric', month: 'long', day: 'numeric' })]];
  autoTable(doc, {
    startY: startY,
    head: [],
    body: reportDate,
    theme: 'plain',
    styles: { fontSize: 10, halign: isRTL ? 'right' : 'left' },
    margin: { left: 15, right: 15 }
  });

  startY = doc.lastAutoTable.finalY + 10;

  // الجدول الرئيسي
  autoTable(doc, {
    startY: startY,
    head: [columns.map(col => col.header)],
    body: data.map(row => columns.map(col => {
      const value = col.accessor(row);
      if (typeof value === 'number') {
        return value.toLocaleString('ar-EG', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
      }
      return value || '-';
    })),
    theme: 'striped',
    headStyles: { fillColor: [255, 140, 0], textColor: 255, fontStyle: 'bold' },
    styles: { 
      fontSize: isRTL ? 10 : 9, 
      halign: isRTL ? 'right' : 'left',
      font: isRTL ? 'Arial' : 'helvetica'
    },
    margin: { left: 15, right: 15 },
    didDrawPage: function (data) {
      // إضافة علامة مائية في كل صفحة
      if (logoBase64) {
        doc.setGState(doc.GState({ opacity: 0.08 }));
        const logoWidth = 120;
        const logoHeight = 120;
        const centerX = (pageWidth - logoWidth) / 2;
        const centerY = (pageHeight - logoHeight) / 2;
        doc.addImage(logoBase64, 'PNG', centerX, centerY, logoWidth, logoHeight);
        doc.setGState(doc.GState({ opacity: 1 }));
      }
    }
  });

  // التذييل
  const finalY = doc.lastAutoTable.finalY + 10;
  autoTable(doc, {
    startY: finalY,
    head: [],
    body: [[t.reportFooter]],
    theme: 'plain',
    styles: { fontSize: 7, textColor: [128, 128, 128], halign: 'center' },
    margin: { left: 15, right: 15 }
  });

  return doc;
};

// طباعة مباشرة
export const printInvoice = async (invoice, type, tenantName, logoPath, language = 'ar', invoiceItems = []) => {
  const doc = await generateInvoicePDF(invoice, type, tenantName, logoPath, language, invoiceItems);
  doc.autoPrint();
  window.open(doc.output('bloburl'), '_blank');
};

// تصدير PDF
export const exportInvoicePDF = async (invoice, type, tenantName, logoPath, language = 'ar', invoiceItems = []) => {
  const doc = await generateInvoicePDF(invoice, type, tenantName, logoPath, language, invoiceItems);
  const fileName = `${type === 'in' ? 'invoice_in' : 'invoice_out'}_${invoice.invoice_number || invoice.id?.substring(0, 8) || Date.now()}.pdf`;
  doc.save(fileName);
};

// تصدير تقرير PDF
export const exportReportPDF = async (title, data, columns, tenantName, logoPath, language = 'ar') => {
  const doc = await generateReportPDF(title, data, columns, tenantName, logoPath, language);
  const fileName = `report_${Date.now()}.pdf`;
  doc.save(fileName);
};
